package com.xtensus.passosyf.entities;

// Generated 23 ao�t 2012 12:50:52 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Commission generated by hbm2java
 */
@Entity
@Table(name = "commission")
public class Commission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6803983363688385110L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "commissionReference", unique = true, nullable = false)
	private Integer commissionReference;

	private String commissionIntitule;
	private String commissionObjet;
	@Column(name = "commisssionPresidentMatricule")
	private Integer commisssionPresidentMatricule;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(length = 19)
	private Date commissionDateCreation;

	private Integer commissionNbrMembres;

	// private CommissionType commissionType;

//	@JsonProperty(access = Access.WRITE_ONLY)
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "etatId", nullable = false)
	private Etat etat;

	@Column(name = "commissionIdentifiant", unique = true)
	private String commissionIdentifiant;
	@Column(name = "dateEffetCommission")
	private Date dateEffetCommission;
	@Column(name = "dateFinCommission")
	private Date dateFinCommission;

//	private Set<Reunion>  reunion ; 
//	private Set<Utilisateurs> utilisateurses = new HashSet<Utilisateurs>(0);
	
	@ManyToMany(fetch = FetchType.LAZY)

	@JoinTable(name = "commissionappeloffre",
	           joinColumns = { @JoinColumn(name = "commissionReference", nullable = false, updatable = false) },
	           inverseJoinColumns = { @JoinColumn(name = "appelOffreReference", nullable = false, updatable = false) })
		private Set<AppelOffres> appelOffres = new HashSet<AppelOffres>(0);

	
	//constructor
	public Commission(Integer commissionReference, String commissionIntitule, String commissionObjet,
			Integer commisssionPresidentMatricule, Date commissionDateCreation, Integer commissionNbrMembres, Etat etat,
			String commissionIdentifiant, Date dateEffetCommission, Date dateFinCommission,Set<AppelOffres> appelOffres) {
		super();
		this.commissionReference = commissionReference;
		this.commissionIntitule = commissionIntitule;
		this.commissionObjet = commissionObjet;
		this.commisssionPresidentMatricule = commisssionPresidentMatricule;
		this.commissionDateCreation = commissionDateCreation;
		this.commissionNbrMembres = commissionNbrMembres;
		this.etat = etat;
		this.commissionIdentifiant = commissionIdentifiant;
		this.dateEffetCommission = dateEffetCommission;
		this.dateFinCommission = dateFinCommission;
		this.appelOffres=appelOffres;
	}
	
	
	public Commission() {
		super();

	}

	

	//getters&setters
	public Integer getCommissionReference() {
		return commissionReference;
	}

	public void setCommissionReference(Integer commissionReference) {
		this.commissionReference = commissionReference;
	}

	public String getCommissionIntitule() {
		return commissionIntitule;
	}

	public void setCommissionIntitule(String commissionIntitule) {
		this.commissionIntitule = commissionIntitule;
	}

	public String getCommissionObjet() {
		return commissionObjet;
	}

	public void setCommissionObjet(String commissionObjet) {
		this.commissionObjet = commissionObjet;
	}

	public Integer getCommisssionPresidentMatricule() {
		return commisssionPresidentMatricule;
	}

	public void setCommisssionPresidentMatricule(Integer commisssionPresidentMatricule) {
		this.commisssionPresidentMatricule = commisssionPresidentMatricule;
	}

	public Date getCommissionDateCreation() {
		return commissionDateCreation;
	}

	public void setCommissionDateCreation(Date commissionDateCreation) {
		this.commissionDateCreation = commissionDateCreation;
	}

	public Integer getCommissionNbrMembres() {
		return commissionNbrMembres;
	}

	public void setCommissionNbrMembres(Integer commissionNbrMembres) {
		this.commissionNbrMembres = commissionNbrMembres;
	}

	public Etat getEtat() {
		return etat;
	}

	public void setEtat(Etat etat) {
		this.etat = etat;
	}

	public String getCommissionIdentifiant() {
		return commissionIdentifiant;
	}

	public void setCommissionIdentifiant(String commissionIdentifiant) {
		this.commissionIdentifiant = commissionIdentifiant;
	}

	public Date getDateEffetCommission() {
		return dateEffetCommission;
	}

	public void setDateEffetCommission(Date dateEffetCommission) {
		this.dateEffetCommission = dateEffetCommission;
	}

	public Date getDateFinCommission() {
		return dateFinCommission;
	}

	public void setDateFinCommission(Date dateFinCommission) {
		this.dateFinCommission = dateFinCommission;
	}


	@Override
	public String toString() {
		return "Commission [commissionReference=" + commissionReference + ", commissionIntitule=" + commissionIntitule
				+ ", commissionObjet=" + commissionObjet + ", commisssionPresidentMatricule="
				+ commisssionPresidentMatricule + ", commissionDateCreation=" + commissionDateCreation
				+ ", commissionNbrMembres=" + commissionNbrMembres + ", etatId=" + etat + ", commissionIdentifiant="
				+ commissionIdentifiant + ", dateEffetCommission=" + dateEffetCommission + ", dateFinCommission="
				+ dateFinCommission + "]";
	}



//
//	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "commissions")
//	public Set<Utilisateurs> getUtilisateurses() {
//		return this.utilisateurses;
//	}
//
//	public void setUtilisateurses(Set<Utilisateurs> utilisateurses) {
//		this.utilisateurses = utilisateurses;
//	}
//
	public Set<AppelOffres> getAppelOffres() {
		return this.appelOffres;
	}
	
	public void setAppelOffres(Set<AppelOffres> appelOffres) {
		this.appelOffres = appelOffres;
	}

}
