package com.xtensus.passosyf.entities;

// Generated 23 ao�t 2012 12:50:52 by Hibernate Tools 3.4.0.Beta1

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
//import java.util.HashSet;
//import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
//import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
//import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modereglement generated by hbm2java
 */
@Entity
@Table(name = "modereglement")
public class ModeReglement  implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(nullable = false , insertable = false , updatable = false)
	private Integer modeReglementId;
	private String modeReglementLibelle;
	//private Set<Avance> avances = new HashSet<Avance>(0);
    //private Set<AppelOffre> appeloffres = new HashSet<AppelOffre>();

	
	//Constructor
	public ModeReglement() {
	}

//	public Modereglement(String modeReglementLibelle, Set<Avance> avances,
//			Set<AppelOffre> appeloffres) {
//		this.modeReglementLibelle = modeReglementLibelle;
//		this.avances = avances;
//		this.appeloffres = appeloffres;
//
//	}


	//getters&setters
	public Integer getModeReglementId() {
		return this.modeReglementId;
	}

	public void setModeReglementId(Integer modeReglementId) {
		this.modeReglementId = modeReglementId;
	}

	@Column(name = "modeReglementLibelle", length = 254)
	public String getModeReglementLibelle() {
		return this.modeReglementLibelle;
	}

	public void setModeReglementLibelle(String modeReglementLibelle) {
		this.modeReglementLibelle = modeReglementLibelle;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modereglement")
//	public Set<Avance> getAvances() {
//		return this.avances;
//	}
//
//	public void setAvances(Set<Avance> avances) {
//		this.avances = avances;
//	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modereglement")
//	public Set<AppelOffre> getAppeloffres() {
//		return this.appeloffres;
//	}
//
//	public void setAppeloffres(Set<AppelOffre> appeloffres) {
//		this.appeloffres = appeloffres;
//	}
}
